### ISSUE TITLE
goldrake class

### ISSUE THREAD

**Issue by CorradoLanera** [CorradoLanera/goldrake#1]
## Base setup
- [x] create the class with the decided components and attributes
- [x] test the correctness type of inputs provided by the user

## Components creation
- [ ] used_data (by sampler #2 ):
  - [ ] remove balancing variables;
  - [ ] create original ids to match rownumbers of orginal data;
  - [ ] create (balancing) group ids/factor (by #4 );
- [ ] reviewers attribute constructor if some names are provided (#3 );
- [x] original_data.

## Attributes setup
- [x] reviewers;
- [ ] gold_classes: check it is a character (by set_gold_class() #5 );
- [ ] balanced_variables: check it is a subsed of the original data's names (by balancer #4 );
- [ ] max_sampled: compute default max sampled from the input provided (by sampler #2 ).
